//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoligrafObPostnova.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.Rental = new HashSet<Rental>();
        }
    
        public int Id { get; set; }
        public int IdType { get; set; }
        public string Name { get; set; }
    
        public virtual EquipmentType EquipmentType { get; set; }
        public virtual ICollection<Rental> Rental { get; set; }
    }
}
